install.packages("psych")
library(psych)
# solo R
cor(hc.net, use="pairwise.complete.obs", method="pearson")
# R and P 
corr.test(hc.net,hc.net, use = "pairwise",method="pearson",adjust="holm",alpha=.05)
# Confidence interval
cormatrix_ci_hc.net <-corr.test(hc.net,hc.net, use = "pairwise",method="pearson",adjust="holm",alpha=.05)
print(cormatrix_ci_hc.net, short=FALSE)
View(cormatrix_ci_hc.net)
#export matrix as csv file
write.csv(cormatrix_ci_hc.net$r, "cormatrix_ci_hc.net_r.csv")
write.csv(cormatrix_ci_hc.net$p, "cormatrix_ci_hc.net_p.csv")
write.csv(cormatrix_ci_hc.net$ci, "cormatrix_ci_hc.net_ci.csv")
write.csv(cormatrix_ci_hc.net$p.adj, "cormatrix_ci_hc.net_padj.csv")
#import"cormatrix_ci_hc.net_padj.csv" ->import dataset from text base->heading:yes->rowname as first column->string as factors
#correlation matrix graph using corrplot

# positive networks


# Calculate the correlation matrix with p-values
corr.test_result <- corr.test(hc.net, hc.net, use = "pairwise", method = "pearson", adjust = "holm", alpha = 0.05)

# Extract the correlation matrix and p-values
r_matrix <- corr.test_result$r
p_matrix <- corr.test_result$p


p.yes<-cormatrix_ci_hc.net_p<0.025
r.val=cormatrix_ci_hc.net$r
p.yes.r<-r.val*p.yes
p.yes.r<-(p.yes.r)> 0.71
p.yes.rr<-p.yes.r*r.val
adjm<-as.matrix(p.yes.rr)
install.packages("igraph")
library(igraph)
network<- graph_from_adjacency_matrix(adjm, mode="undirected", weighted=TRUE, diag=FALSE)
network
V(network)
E(network)$weight
plot(network, vertex.label=V(network)$name, vertex.size=15, vertex.label.cex = 2, vertex.label.dist = 3.5)


plot.igraph(network, vertex.label=V(network)$name, layout=layout.circle, edge.color="black", edge.width=E(network)$weight)
node.name<-V(network)$name
plot.igraph(network, vertex.label=node.name, layout=layout.circle, edge.color="black", edge.width=(E(network)$weight)*1)

#node size by Fos density 

cor
r<- range(adjm)
mean(hc.net$FP, na.rm=TRUE)
mean(hc.net$M1)
mean(hc.net$M2)
mean(hc.net$S1)
mean(hc.net$SS)
mean(hc.net$GA)
mean(hc.net$VA)
mean(hc.net$AuA)
mean(hc.net$ViA,na.rm=TRUE)
mean(hc.net$dACC)
mean(hc.net$Vacc)
mean(hc.net$PL,na.rm=TRUE)
mean(hc.net$IL,na.rm=TRUE)
mean(hc.net$OA,na.rm=TRUE)
mean(hc.net$AU)
mean(hc.net$RS)
mean(hc.net$AA)
mean(hc.net$TeAA)
mean(hc.net$Prh)
mean(hc.net$Ech,na.rm=TRUE)
mean(hc.net$aOn, na.rm=TRUE)
mean(hc.net$TT, na.rm=TRUE)
mean(hc.net$DPA, na.rm=TRUE)
mean(hc.net$PC)
mean(hc.net$CCA,na.rm=TRUE)
mean(hc.net$PAA,na.rm=TRUE)
mean(hc.net$CA1)
mean(hc.net$CA2)
mean(hc.net$CA3)
mean(hc.net$DG)
mean(hc.net$FC,na.rm=TRUE)
mean(hc.net$IG)
mean(hc.net$lpEC)
mean(hc.net$Sub,na.rm=TRUE)
mean(hc.net$proSub,na.rm=TRUE)
mean(hc.net$Clst)
mean(hc.net$dEPn)
mean(hc.net$vEPn)
mean(hc.net$LAn)
mean(hc.net$BLA, na.rm=TRUE)
mean(hc.net$BMe, na.rm=TRUE)
mean(hc.net$PAn,na.rm=TRUE)
mean(hc.net$DLS)
mean(hc.net$DMS)
mean(hc.net$NACC.SHELL)
mean(hc.net$NACC.CORE)
mean(hc.net$FStr, na.rm=TRUE)
mean(hc.net$OT)
mean(hc.net$LSN, na.rm=TRUE)
mean(hc.net$SFn, na.rm=TRUE)
mean(hc.net$aAA,na.rm=TRUE)
mean(hc.net$CA,na.rm=TRUE)
mean(hc.net$IAn,na.rm=TRUE)
mean(hc.net$MAn,na.rm=TRUE)
mean(hc.net$Gpe,na.rm=TRUE)
mean(hc.net$Gpi,na.rm=TRUE)
mean(hc.net$SubInn)
mean(hc.net$MGCn)
mean(hc.net$MSn, na.rm=TRUE)
mean(hc.net$DBn)
mean(hc.net$TnS, na.rm=TRUE)
mean(hc.net$BNST, na.rm=TRUE)
mean(hc.net$VALCT, na.rm=TRUE)
mean(hc.net$VMT)
mean(hc.net$VPLT)
mean(hc.net$VPMT)
mean(hc.net$PTTn, na.rm=TRUE)
mean(hc.net$MGC,na.rm=TRUE)
mean(hc.net$dLGC)
mean(hc.net$LPT)
mean(hc.net$PCT,na.rm=TRUE)
mean(hc.net$PlnT,na.rm=TRUE)
mean(hc.net$EnT)
mean(hc.net$AVT,na.rm=TRUE)
mean(hc.net$AMn,na.rm=TRUE)
mean(hc.net$IADT,na.rm=TRUE)
mean(hc.net$IMDT,na.rm=TRUE)
mean(hc.net$MDT)
mean(hc.net$SMT,na.rm=TRUE)
mean(hc.net$pRE,na.rm=TRUE)
mean(hc.net$PVT)
mean(hc.net$PT,na.rm=TRUE)
mean(hc.net$RE,na.rm=TRUE)
mean(hc.net$XiT,na.rm=TRUE)
mean(hc.net$Rh,na.rm=TRUE)
mean(hc.net$CMT)
mean(hc.net$PCn,na.rm=TRUE)
mean(hc.net$CLT,na.rm=TRUE)
mean(hc.net$RT)
mean(hc.net$IGLLGC, na.rm=TRUE)
mean(hc.net$vlLGC , na.rm=TRUE)
mean(hc.net$subGn, na.rm=TRUE)
mean(hc.net$MHb)
mean(hc.net$LHb,na.rm=TRUE)
mean(hc.net$SON,na.rm=TRUE)
mean(hc.net$PVH,na.rm=TRUE)
mean(hc.net$IPVH,na.rm=TRUE)
mean(hc.net$ArH,na.rm=TRUE)
mean(hc.net$ADPO,na.rm=TRUE)
mean(hc.net$AVPO, na.rm=TRUE)
mean(hc.net$AVPV, na.rm=TRUE)
mean(hc.net$DMH,na.rm=TRUE)
mean(hc.net$MePO, na.rm=TRUE)
mean(hc.net$MPA)
mean(hc.net$PSN, na.rm=TRUE)
mean(hc.net$SPZ,na.rm=TRUE)
mean(hc.net$SCN,na.rm=TRUE)
mean(hc.net$AHN,na.rm=TRUE)
mean(hc.net$SMN,na.rm=TRUE)
mean(hc.net$MPO,na.rm=TRUE)
mean(hc.net$VMHn,na.rm=TRUE)
mean(hc.net$PHn, na.rm=TRUE)
mean(hc.net$LHA)
mean(hc.net$LPO)
mean(hc.net$PSTN, na.rm=TRUE)
mean(hc.net$STN,na.rm=TRUE)
mean(hc.net$TN,na.rm=TRUE)
mean(hc.net$ZI)
mean(hc.net$FF,na.rm=TRUE)
mean(hc.net$SCO, na.rm=TRUE)
mean(hc.net$reSN,na.rm=TRUE)
mean(hc.net$VTA,na.rm=TRUE)
mean(hc.net$PAG,na.rm=TRUE)
mean(hc.net$PreCN, na.rm=TRUE)
mean(hc.net$APTN, na.rm=TRUE)
mean(hc.net$cSN,na.rm=TRUE)
a1<-mean(hc.net$FP)
a2<-mean(hc.net$M1)
a3<-mean(hc.net$M2)
a4<-mean(hc.net$S1)
a11<-mean(hc.net$SS)
a12<-mean(hc.net$GA)
a13<-mean(hc.net$VA)
a14<-mean(hc.net$AuA)
a18<-mean(hc.net$ViA)
a24<-mean(hc.net$dACC)
a25<-mean(hc.net$Vacc)
a26<-mean(hc.net$PL)
a27<-mean(hc.net$IL)
a28<-mean(hc.net$OA)
a31<-mean(hc.net$AU)
a34<-mean(hc.net$RS)
a37<-mean(hc.net$AA)
a39<-mean(hc.net$TeAA)
a40<-mean(hc.net$Prh)
a41<-mean(hc.net$Ech)
a43<-mean(hc.net$aOn)
a44<-mean(hc.net$TT)
a46<-mean(hc.net$DPA)
a47<-mean(hc.net$PC)
a49<-mean(hc.net$CCA)
a52<-mean(hc.net$PAA)
a54<-mean(hc.net$CA1)
a55<-mean(hc.net$CA2)
a56<-mean(hc.net$CA3)
a57<-mean(hc.net$DG)
a58<-mean(hc.net$FC)
a59<-mean(hc.net$IG)
a60<-mean(hc.net$lpEC)
a62<-mean(hc.net$Sub)
a63<-mean(hc.net$proSub)
a66<-mean(hc.net$Clst)
a67<-mean(hc.net$dEPn)
a68<-mean(hc.net$vEPn)
a69<-mean(hc.net$LAn)
a70<-mean(hc.net$BLA)
a73<-mean(hc.net$BMe)
a75<-mean(hc.net$PAn)
a76<-mean(hc.net$DLS)
a77<-mean(hc.net$DMS)
a78<-mean(hc.net$NACC.SHELL)
a79<-mean(hc.net$NACC.CORE)
a80<-mean(hc.net$FStr)
a81<-mean(hc.net$OT)
a82<-mean(hc.net$LSN)
a85<-mean(hc.net$SFn)
a87<-mean(hc.net$aAA)
a89<-mean(hc.net$CA)
a92<-mean(hc.net$IAn)
a93<-mean(hc.net$MAn)
a94<-mean(hc.net$Gpe)
a95<-mean(hc.net$Gpi)
a96<-mean(hc.net$SubInn)
a97<-mean(hc.net$MGCn)
a98<-mean(hc.net$MSn)
a99<-mean(hc.net$DBn)
a100<-mean(hc.net$TnS)
a101<-mean(hc.net$BNST)
a103<-mean(hc.net$VALCT)
a104<-mean(hc.net$VMT)
a105<-mean(hc.net$VPLT)
a107<-mean(hc.net$VPMT)
a109<-mean(hc.net$PTTn)
a113<-mean(hc.net$MGC)
a115<-mean(hc.net$dLGC)
a118<-mean(hc.net$LPT)
a119<-mean(hc.net$PCT)
a120<-mean(hc.net$PlnT)
a122<-mean(hc.net$EnT)
a123<-mean(hc.net$AVT)
a124<-mean(hc.net$AMn)
a128<-mean(hc.net$IADT)
a130<-mean(hc.net$IMDT)
a131<-mean(hc.net$MDT)
a132<-mean(hc.net$SMT)
a133<-mean(hc.net$pRE)
a134<-mean(hc.net$PVT)
a135<-mean(hc.net$PT)
a136<-mean(hc.net$RE)
a137<-mean(hc.net$XiT)
a138<-mean(hc.net$Rh)
a139<-mean(hc.net$CMT)
a140<-mean(hc.net$PCn)
a141<-mean(hc.net$CLT)
a144<-mean(hc.net$RT)
a145<-mean(hc.net$IGLLGC)
a147<-mean(hc.net$vlLGC)
a148<-mean(hc.net$subGn)
a149<-mean(hc.net$MHb)
a150<-mean(hc.net$LHb)
a151<-mean(hc.net$SON)
a153<-mean(hc.net$PVH)
a155<-mean(hc.net$IPVH)
a156<-mean(hc.net$ArH,na.rm=TRUE)
a157<-mean(hc.net$ADPO)
a158<-mean(hc.net$AVPO)
a159<-mean(hc.net$AVPV)
a160<-mean(hc.net$DMH)
a161<-mean(hc.net$MePO)
a162<-mean(hc.net$MPA)
a165<-mean(hc.net$PSN)
a168<-mean(hc.net$SPZ)
a169<-mean(hc.net$SCN,na.rm=TRUE)
a173<-mean(hc.net$AHN)
a179<-mean(hc.net$SMN)
a182<-mean(hc.net$MPO)
a186<-mean(hc.net$VMHn)
a187<-mean(hc.net$PHn)
a188<-mean(hc.net$LHA)
a189<-mean(hc.net$LPO)
a191<-mean(hc.net$PSTN)
a194<-mean(hc.net$STN)
a195<-mean(hc.net$TN)
a196<-mean(hc.net$ZI)
a197<-mean(hc.net$FF)
a200<-mean(hc.net$SCO)
a201<-mean(hc.net$reSN)
a202<-mean(hc.net$VTA)
a206<-mean(hc.net$PAG)
a207<-mean(hc.net$PreCN)
a210<-mean(hc.net$APTN)
a222<-mean(hc.net$cSN)

data<-data.frame(a1,a2,a3,a4,a11,a12,a13,a14,a18,a24,a25,a26,a27,a28,a31,a34,a37,a39,a40,a41,a43,a44,a46,a47,a49,a52,a54,a55,a56,a57,a58,a59,a60,a62,a63,a66,a67,a68,a69,a70,a73,a75,a76,a77,a78,a79,a80,a81,a82,a85,a87,a89,a92,a93,a94,a95,a96,a97,a98,a99,a100,a101,a103,a104,a105,a107,a109,a113,a115,a118,a119,a120,a122,a123,a124,a128,a130,a131,a132,a133,a134,a135,a136,a137,a138,a139,a140,a141,a144,a145,a147,a148,a149,a150,a151,a153,a155,a156,a157,a158,a159,a160,a161,a162,a165,a168,a169,a173,a179,a182,a186,a187,a188,a189,a191,a194,a195,a196,a197,a200,a201,a202,a206,a207,a210,a222)

v<-setNames(c(data), c(node.name))
print(v)
node.size<-unlist(v)
plot(node.size)
node.size.1000<-node.size*1000
plot(node.size.1000)


# Nodes size=degree
d<-degree(network)
plot.igraph(network, vertex.label=V(network)$name, vertex.label.dist=1, layout=layout.circle, edge.color="black", edge.width=(E(network)$weight)*2, vertex.size=degree(network)+1)

g=get.edgelist(network)
write.csv(g, file = "g.csv", row.names = FALSE, na="")
if(!"RCy3" %in% installed.packages()){
  install.packages("BiocManager")
  BiocManager::install("RCy3")
}
library(igraph)
library(RCy3)



createNetworkFromIgraph(network,"hcnet")





