install.packages("psych")
library(psych)
# solo R
cor(ss.net, use="pairwise.complete.obs", method="pearson")
# R and P 
corr.test(ss.net,ss.net, use = "pairwise",method="pearson",adjust="holm",alpha=.05)
# Confidence interval
cormatrix_ci_ss.net <-corr.test(ss.net,ss.net, use = "pairwise",method="pearson",adjust="holm",alpha=.05)
print(cormatrix_ci_ss.net, short=FALSE)
View(cormatrix_ci_ss.net)
#export matrix as csv file
write.csv(cormatrix_ci_ss.net$r, "cormatrix_ci_ss.net_r.csv")
write.csv(cormatrix_ci_ss.net$p, "cormatrix_ci_ss.net_p.csv")
write.csv(cormatrix_ci_ss.net$ci, "cormatrix_ci_ss.net_ci.csv")
write.csv(cormatrix_ci_ss.net$p.adj, "cormatrix_ci_ss.net_padj.csv")
#import"cormatrix_ci_ss.net_padj.csv" ->import dataset from text base->heading:yes->rowname as first column->string as factors
#correlation matrix graph using corrplot


p.yes<-cormatrix_ci_ss.net_p<0.04
r.val=cormatrix_ci_ss.net$r
p.yes.r<-r.val*p.yes
p.yes.r<-(p.yes.r)> 0.65
p.yes.rr<-p.yes.r*r.val
adjm<-as.matrix(p.yes.rr)
install.packages("igraph")
library(igraph)
network<- graph_from_adjacency_matrix(adjm, mode="undirected", weighted=TRUE, diag=FALSE)
network
V(network)
E(network)$weight
plot(network, vertex.label=V(network)$name, vertex.size=15, vertex.label.cex = 2, vertex.label.dist = 3.5)


plot.igraph(network, vertex.label=V(network)$name, layout=layout.circle, edge.color="black", edge.width=E(network)$weight)
node.name<-V(network)$name
plot.igraph(network, vertex.label=node.name, layout=layout.circle, edge.color="black", edge.width=(E(network)$weight)*1)

#node size by Fos density 

cor
r<- range(adjm)
mean(ss.net$FP, na.rm=TRUE)
mean(ss.net$M1)
mean(ss.net$M2)
mean(ss.net$S1)
mean(ss.net$SS)
mean(ss.net$GA)
mean(ss.net$VA)
mean(ss.net$AuA)
mean(ss.net$ViA,na.rm=TRUE)
mean(ss.net$dACC)
mean(ss.net$Vacc)
mean(ss.net$PL,na.rm=TRUE)
mean(ss.net$IL,na.rm=TRUE)
mean(ss.net$OA,na.rm=TRUE)
mean(ss.net$AU)
mean(ss.net$RS)
mean(ss.net$AA)
mean(ss.net$TeAA)
mean(ss.net$Prh)
mean(ss.net$Ech,na.rm=TRUE)
mean(ss.net$aOn, na.rm=TRUE)
mean(ss.net$TT, na.rm=TRUE)
mean(ss.net$DPA, na.rm=TRUE)
mean(ss.net$PC)
mean(ss.net$CCA,na.rm=TRUE)
mean(ss.net$PAA,na.rm=TRUE)
mean(ss.net$CA1)
mean(ss.net$CA2)
mean(ss.net$CA3)
mean(ss.net$DG)
mean(ss.net$FC,na.rm=TRUE)
mean(ss.net$IG)
mean(ss.net$lpEC)
mean(ss.net$Sub,na.rm=TRUE)
mean(ss.net$proSub,na.rm=TRUE)
mean(ss.net$Clst)
mean(ss.net$dEPn)
mean(ss.net$vEPn)
mean(ss.net$LAn)
mean(ss.net$BLA, na.rm=TRUE)
mean(ss.net$BMe, na.rm=TRUE)
mean(ss.net$PAn,na.rm=TRUE)
mean(ss.net$DLS)
mean(ss.net$DMS)
mean(ss.net$NACC.SHELL)
mean(ss.net$NACC.CORE)
mean(ss.net$FStr, na.rm=TRUE)
mean(ss.net$OT)
mean(ss.net$LSN, na.rm=TRUE)
mean(ss.net$SFn, na.rm=TRUE)
mean(ss.net$aAA,na.rm=TRUE)
mean(ss.net$CA,na.rm=TRUE)
mean(ss.net$IAn,na.rm=TRUE)
mean(ss.net$MAn,na.rm=TRUE)
mean(ss.net$Gpe,na.rm=TRUE)
mean(ss.net$Gpi,na.rm=TRUE)
mean(ss.net$SubInn)
mean(ss.net$MGCn)
mean(ss.net$MSn, na.rm=TRUE)
mean(ss.net$DBn)
mean(ss.net$TnS, na.rm=TRUE)
mean(ss.net$BNST, na.rm=TRUE)
mean(ss.net$VALCT, na.rm=TRUE)
mean(ss.net$VMT)
mean(ss.net$VPLT)
mean(ss.net$VPMT)
mean(ss.net$PTTn, na.rm=TRUE)
mean(ss.net$MGC,na.rm=TRUE)
mean(ss.net$dLGC)
mean(ss.net$LPT)
mean(ss.net$PCT,na.rm=TRUE)
mean(ss.net$PlnT,na.rm=TRUE)
mean(ss.net$EnT)
mean(ss.net$AVT,na.rm=TRUE)
mean(ss.net$AMn,na.rm=TRUE)
mean(ss.net$IADT,na.rm=TRUE)
mean(ss.net$IMDT,na.rm=TRUE)
mean(ss.net$MDT)
mean(ss.net$SMT,na.rm=TRUE)
mean(ss.net$pRE,na.rm=TRUE)
mean(ss.net$PVT)
mean(ss.net$PT,na.rm=TRUE)
mean(ss.net$RE,na.rm=TRUE)
mean(ss.net$XiT,na.rm=TRUE)
mean(ss.net$Rh,na.rm=TRUE)
mean(ss.net$CMT)
mean(ss.net$PCn,na.rm=TRUE)
mean(ss.net$CLT,na.rm=TRUE)
mean(ss.net$RT)
mean(ss.net$IGLLGC, na.rm=TRUE)
mean(ss.net$vlLGC , na.rm=TRUE)
mean(ss.net$subGn, na.rm=TRUE)
mean(ss.net$MHb)
mean(ss.net$LHb,na.rm=TRUE)
mean(ss.net$SON,na.rm=TRUE)
mean(ss.net$PVH,na.rm=TRUE)
mean(ss.net$IPVH,na.rm=TRUE)
mean(ss.net$ArH,na.rm=TRUE)
mean(ss.net$ADPO,na.rm=TRUE)
mean(ss.net$AVPO, na.rm=TRUE)
mean(ss.net$AVPV, na.rm=TRUE)
mean(ss.net$DMH,na.rm=TRUE)
mean(ss.net$MePO, na.rm=TRUE)
mean(ss.net$MPA)
mean(ss.net$PSN, na.rm=TRUE)
mean(ss.net$SPZ,na.rm=TRUE)
mean(ss.net$SCN,na.rm=TRUE)
mean(ss.net$AHN,na.rm=TRUE)
mean(ss.net$SMN,na.rm=TRUE)
mean(ss.net$MPO,na.rm=TRUE)
mean(ss.net$VMHn,na.rm=TRUE)
mean(ss.net$PHn, na.rm=TRUE)
mean(ss.net$LHA)
mean(ss.net$LPO)
mean(ss.net$PSTN, na.rm=TRUE)
mean(ss.net$STN,na.rm=TRUE)
mean(ss.net$TN,na.rm=TRUE)
mean(ss.net$ZI)
mean(ss.net$FF,na.rm=TRUE)
mean(ss.net$SCO, na.rm=TRUE)
mean(ss.net$reSN,na.rm=TRUE)
mean(ss.net$VTA,na.rm=TRUE)
mean(ss.net$PAG,na.rm=TRUE)
mean(ss.net$PreCN, na.rm=TRUE)
mean(ss.net$APTN, na.rm=TRUE)
mean(ss.net$cSN,na.rm=TRUE)
a1<-mean(ss.net$FP)
a2<-mean(ss.net$M1)
a3<-mean(ss.net$M2)
a4<-mean(ss.net$S1)
a11<-mean(ss.net$SS)
a12<-mean(ss.net$GA)
a13<-mean(ss.net$VA)
a14<-mean(ss.net$AuA)
a18<-mean(ss.net$ViA)
a24<-mean(ss.net$dACC)
a25<-mean(ss.net$Vacc)
a26<-mean(ss.net$PL)
a27<-mean(ss.net$IL)
a28<-mean(ss.net$OA)
a31<-mean(ss.net$AU)
a34<-mean(ss.net$RS)
a37<-mean(ss.net$AA)
a39<-mean(ss.net$TeAA)
a40<-mean(ss.net$Prh)
a41<-mean(ss.net$Ech)
a43<-mean(ss.net$aOn)
a44<-mean(ss.net$TT)
a46<-mean(ss.net$DPA)
a47<-mean(ss.net$PC)
a49<-mean(ss.net$CCA)
a52<-mean(ss.net$PAA)
a54<-mean(ss.net$CA1)
a55<-mean(ss.net$CA2)
a56<-mean(ss.net$CA3)
a57<-mean(ss.net$DG)
a58<-mean(ss.net$FC)
a59<-mean(ss.net$IG)
a60<-mean(ss.net$lpEC)
a62<-mean(ss.net$Sub)
a63<-mean(ss.net$proSub)
a66<-mean(ss.net$Clst)
a67<-mean(ss.net$dEPn)
a68<-mean(ss.net$vEPn)
a69<-mean(ss.net$LAn)
a70<-mean(ss.net$BLA)
a73<-mean(ss.net$BMe)
a75<-mean(ss.net$PAn)
a76<-mean(ss.net$DLS)
a77<-mean(ss.net$DMS)
a78<-mean(ss.net$NACC.SHELL)
a79<-mean(ss.net$NACC.CORE)
a80<-mean(ss.net$FStr)
a81<-mean(ss.net$OT)
a82<-mean(ss.net$LSN)
a85<-mean(ss.net$SFn)
a87<-mean(ss.net$aAA)
a89<-mean(ss.net$CA)
a92<-mean(ss.net$IAn)
a93<-mean(ss.net$MAn)
a94<-mean(ss.net$Gpe)
a95<-mean(ss.net$Gpi)
a96<-mean(ss.net$SubInn)
a97<-mean(ss.net$MGCn)
a98<-mean(ss.net$MSn)
a99<-mean(ss.net$DBn)
a100<-mean(ss.net$TnS)
a101<-mean(ss.net$BNST)
a103<-mean(ss.net$VALCT)
a104<-mean(ss.net$VMT)
a105<-mean(ss.net$VPLT)
a107<-mean(ss.net$VPMT)
a109<-mean(ss.net$PTTn)
a113<-mean(ss.net$MGC)
a115<-mean(ss.net$dLGC)
a118<-mean(ss.net$LPT)
a119<-mean(ss.net$PCT)
a120<-mean(ss.net$PlnT)
a122<-mean(ss.net$EnT)
a123<-mean(ss.net$AVT)
a124<-mean(ss.net$AMn)
a128<-mean(ss.net$IADT)
a130<-mean(ss.net$IMDT)
a131<-mean(ss.net$MDT)
a132<-mean(ss.net$SMT)
a133<-mean(ss.net$pRE)
a134<-mean(ss.net$PVT)
a135<-mean(ss.net$PT)
a136<-mean(ss.net$RE)
a137<-mean(ss.net$XiT)
a138<-mean(ss.net$Rh)
a139<-mean(ss.net$CMT)
a140<-mean(ss.net$PCn)
a141<-mean(ss.net$CLT)
a144<-mean(ss.net$RT)
a145<-mean(ss.net$IGLLGC)
a147<-mean(ss.net$vlLGC)
a148<-mean(ss.net$subGn)
a149<-mean(ss.net$MHb)
a150<-mean(ss.net$LHb)
a151<-mean(ss.net$SON)
a153<-mean(ss.net$PVH)
a155<-mean(ss.net$IPVH)
a156<-mean(ss.net$ArH,na.rm=TRUE)
a157<-mean(ss.net$ADPO)
a158<-mean(ss.net$AVPO)
a159<-mean(ss.net$AVPV)
a160<-mean(ss.net$DMH)
a161<-mean(ss.net$MePO)
a162<-mean(ss.net$MPA)
a165<-mean(ss.net$PSN)
a168<-mean(ss.net$SPZ)
a169<-mean(ss.net$SCN,na.rm=TRUE)
a173<-mean(ss.net$AHN)
a179<-mean(ss.net$SMN)
a182<-mean(ss.net$MPO)
a186<-mean(ss.net$VMHn)
a187<-mean(ss.net$PHn)
a188<-mean(ss.net$LHA)
a189<-mean(ss.net$LPO)
a191<-mean(ss.net$PSTN)
a194<-mean(ss.net$STN)
a195<-mean(ss.net$TN)
a196<-mean(ss.net$ZI)
a197<-mean(ss.net$FF)
a200<-mean(ss.net$SCO)
a201<-mean(ss.net$reSN)
a202<-mean(ss.net$VTA)
a206<-mean(ss.net$PAG)
a207<-mean(ss.net$PreCN)
a210<-mean(ss.net$APTN)
a222<-mean(ss.net$cSN)

data<-data.frame(a1,a2,a3,a4,a11,a12,a13,a14,a18,a24,a25,a26,a27,a28,a31,a34,a37,a39,a40,a41,a43,a44,a46,a47,a49,a52,a54,a55,a56,a57,a58,a59,a60,a62,a63,a66,a67,a68,a69,a70,a73,a75,a76,a77,a78,a79,a80,a81,a82,a85,a87,a89,a92,a93,a94,a95,a96,a97,a98,a99,a100,a101,a103,a104,a105,a107,a109,a113,a115,a118,a119,a120,a122,a123,a124,a128,a130,a131,a132,a133,a134,a135,a136,a137,a138,a139,a140,a141,a144,a145,a147,a148,a149,a150,a151,a153,a155,a156,a157,a158,a159,a160,a161,a162,a165,a168,a169,a173,a179,a182,a186,a187,a188,a189,a191,a194,a195,a196,a197,a200,a201,a202,a206,a207,a210,a222)

v<-setNames(c(data), c(node.name))
print(v)
node.size<-unlist(v)
plot(node.size)
node.size.1000<-node.size*1000
plot(node.size.1000)


# Nodes size=degree
d<-degree(network)
plot.igraph(network, vertex.label=V(network)$name, vertex.label.dist=1, layout=layout.circle, edge.color="black", edge.width=(E(network)$weight)*2, vertex.size=degree(network)+1)

g=get.edgelist(network)
write.csv(g, file = "g.csv", row.names = FALSE, na="")
if(!"RCy3" %in% installed.packages()){
  install.packages("BiocManager")
  BiocManager::install("RCy3")
}
library(igraph)
library(RCy3)



createNetworkFromIgraph(network,"ssnet")


# Installazione e caricamento dei pacchetti necessari
install.packages("boot")
library(boot)
library(igraph)
library(influential)
# Identify the connected components of the graph
comp <- components(network)

# Extract the giant component
giant_component <- induced_subgraph(network, which(comp$membership == which.max(comp$csize)))

# Store the original node names
original_node_names <- V(giant_component)$name

# Initialize an empty data frame to store the results
results <- data.frame()

# Set the number of iterations (i.e., number of nodes to remove)
num_iterations <- 30

# Loop through the iterations
for (i in 1:num_iterations) {
  # Calculate the Collective Influence (CI) values
  ci <- collective.influence(giant_component, vertices = V(giant_component), mode = "all", d = 3, verbose = FALSE)
  
  # Get the node with the highest CI value
  max_ci_node <- which.max(ci)
  node_name <- original_node_names[max_ci_node]
  
  # Remove the node with the highest CI value from the network
  giant_component <- delete_vertices(giant_component, max_ci_node)
  
  # Update the original node names vector
  original_node_names <- original_node_names[-max_ci_node]
  
  # Append the results to the data frame
  results <- rbind(results, data.frame(Node_Removed = node_name, CI_Value = max(ci)))
  
  # Write the results to a CSV file
  write.csv(results, "SS_ci_disruption_0.04_d4.csv", row.names = FALSE)
}